import { MetadataRoute } from 'next';
import { getAllBlogPosts } from '@/lib/blog-data';
import { SITEMAP_0_LOCATIONS, SITEMAP_1_LOCATIONS } from '@/lib/sitemap-config';
import { getAllSEOServices } from '@/lib/seo-data';

/**
 * MULTI-SITEMAP USING generateSitemaps
 *
 * This uses Next.js built-in generateSitemaps() function to split into multiple sitemaps:
 *
 * SITEMAP 0: Primary Local & Northwest Areas (36,769 URLs)
 * - Hartbeespoort/Harties and all estates
 * - Pretoria, Centurion, and surrounding areas
 * - Northwest Province (Brits, Rustenburg, Potchefstroom, etc.)
 * - All static pages, blog posts, and location index
 *
 * SITEMAP 1: Extended Gauteng Coverage (27,540 URLs)
 * - Johannesburg and all suburbs
 * - East Rand, West Rand
 * - Midrand, Kempton Park
 * - Vaal Triangle
 *
 * Total: 64,309 URLs across 2 sitemaps
 * Both sitemaps are well under Google's 50,000 URL limit per sitemap
 *
 * Access URLs:
 * - /sitemap.xml (sitemap index - auto-generated by Next.js)
 * - /sitemap/0.xml (sitemap 0)
 * - /sitemap/1.xml (sitemap 1)
 */

const BASE_URL = 'https://www.galeobeauty.com';

const STATIC_PAGES = [
    { path: '', priority: 1.0, changefreq: 'weekly' as const },
    { path: '/prices', priority: 0.9, changefreq: 'weekly' as const },
    { path: '/specials', priority: 0.8, changefreq: 'weekly' as const },
    { path: '/gallery', priority: 0.7, changefreq: 'monthly' as const },
    { path: '/about', priority: 0.6, changefreq: 'monthly' as const },
    { path: '/contact', priority: 0.8, changefreq: 'monthly' as const },
    { path: '/blog', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/careers', priority: 0.5, changefreq: 'monthly' as const },
    { path: '/prices/hart-aesthetics', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/prices/fat-freezing', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/prices/slimming', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/prices/dermalogica', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/prices/ipl', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/prices/makeup', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/prices/medical', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/prices/permanent-makeup', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/prices/pro-skin', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/prices/qms-facial', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/prices/sunbed', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/prices/waxing', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/prices/hair', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/prices/nails', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/prices/lashes', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/prices/hair-extensions', priority: 0.85, changefreq: 'weekly' as const },
    { path: '/services/microblading', priority: 0.85, changefreq: 'monthly' as const },
    { path: '/services/fat-freezing-treatment', priority: 0.85, changefreq: 'monthly' as const },
    { path: '/services/lash-extensions', priority: 0.85, changefreq: 'monthly' as const },
    { path: '/services/lip-fillers', priority: 0.85, changefreq: 'monthly' as const },
    { path: '/services/brazilian-wax', priority: 0.85, changefreq: 'monthly' as const },
    { path: '/services/dermalogica-facial', priority: 0.85, changefreq: 'monthly' as const },
    { path: '/services/nail-art', priority: 0.85, changefreq: 'monthly' as const },
    { path: '/services/massage-therapy', priority: 0.85, changefreq: 'monthly' as const },
];

// Tell Next.js we want to generate multiple sitemaps
export function generateSitemaps() {
    return [
        { id: '0' }, // Sitemap 0: Primary Local & Northwest
        { id: '1' }, // Sitemap 1: Extended Gauteng
    ];
}

export default async function sitemap({ id }: { id: string }): Promise<MetadataRoute.Sitemap> {
    const services = getAllSEOServices();
    const sitemapEntries: MetadataRoute.Sitemap = [];

    if (id === '0') {
        // SITEMAP 0: Primary Local & Northwest Areas
        // Add static pages
        for (const page of STATIC_PAGES) {
            sitemapEntries.push({
                url: `${BASE_URL}${page.path}`,
                lastModified: new Date(),
                changeFrequency: page.changefreq,
                priority: page.priority,
            });
        }

        // Add blog posts
        const blogPosts = getAllBlogPosts();
        for (const post of blogPosts) {
            sitemapEntries.push({
                url: `${BASE_URL}/blog/${post.slug}`,
                lastModified: new Date(post.date),
                changeFrequency: 'monthly',
                priority: 0.8,
            });
        }

        // Add location index
        sitemapEntries.push({
            url: `${BASE_URL}/locations`,
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.9,
        });

        // Add location hubs for SITEMAP_0_LOCATIONS
        for (const location of SITEMAP_0_LOCATIONS) {
            sitemapEntries.push({
                url: `${BASE_URL}/locations/${location}`,
                lastModified: new Date(),
                changeFrequency: 'weekly',
                priority: 0.8,
            });
        }

        // Add location service pages for SITEMAP_0_LOCATIONS
        for (const location of SITEMAP_0_LOCATIONS) {
            for (const service of services) {
                sitemapEntries.push({
                    url: `${BASE_URL}/locations/${location}/${service.slug}`,
                    lastModified: new Date(),
                    changeFrequency: 'monthly',
                    priority: 0.7,
                });
            }
        }
    } else if (id === '1') {
        // SITEMAP 1: Extended Gauteng Coverage
        // Add location hubs for SITEMAP_1_LOCATIONS
        for (const location of SITEMAP_1_LOCATIONS) {
            sitemapEntries.push({
                url: `${BASE_URL}/locations/${location}`,
                lastModified: new Date(),
                changeFrequency: 'weekly',
                priority: 0.8,
            });
        }

        // Add location service pages for SITEMAP_1_LOCATIONS
        for (const location of SITEMAP_1_LOCATIONS) {
            for (const service of services) {
                sitemapEntries.push({
                    url: `${BASE_URL}/locations/${location}/${service.slug}`,
                    lastModified: new Date(),
                    changeFrequency: 'monthly',
                    priority: 0.7,
                });
            }
        }
    }

    return sitemapEntries;
}
